spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://153.126.174.131:5432/ec-pizza-experience
    username: postgres
    password: postgres